### ISSUE TITLE
rxFactors fails with relative paths in Spark CC

### ISSUE THREAD

**Issue by hongooi73** [RevolutionAnalytics/dplyrXdf#40]
``` r
## set compute context to RxSpark
hd <- RxHdfsFileSystem()
mth <- dplyrXdf::copy_to_hdfs(mtcars)
out <- RxXdfData("ftest", fileSystem=hd, createCompositeSet=TRUE)
rxFactors(mth, outFile=out, factorInfo="am")

#Job failed, the last 20 lines of the log are shown below:
    #Internal Error: Fail to execute Hadoop/Spark job. 
    #Caught exception in file: /builddir/ExaRoot/ExaCore/CxAnalysis.cpp, line: 5837. ThreadID: 233486464 Rethrowing. 
    #Error in try({ :  
    #Traceback (most recent call last): 
      #File "/usr/lib64/microsoft-r/3.3/lib64/R/library/RevoScaleR/pythonScripts/common//logScaleR.py", line 1, in <module> 
        #from hdinsight_common import hdinsightlogging 
      #File "/usr/local/lib/python2.7/dist-packages/hdinsight_common/hdinsightlogging.py", line 8, in <module> 
        #import utilities 
      #File "/usr/local/lib/python2.7/dist-packages/hdinsight_common/utilities.py", line 10, in <module> 
        #import Constants 
      #File "/usr/local/lib/python2.7/dist-packages/hdinsight_common/Constants.py", line 3, in <module> 
        #from hdinsight_role_env import RoleEnv 
      #File "/usr/lib/python2.7/dist-packages/hdinsight_role_env/RoleEnv.py", line 3, in <module> 
        #from watchdog.observers import Observer   
    #ImportError: No module named watchdog.observers 
    #Error:  Error in try({ :  
      
    #======  ed1-hdi21 (Master HPA Process) has completed run at Tue Jul 11 20:32:36 2017  ====== 
    #>  
    #>  
#For the complete log, please refer to the log file C:\Users\hongooi\AppData\Local\Temp\MRSArchive\MRSLog-e6831631a5.log 

#Error in rxuHandleClusterJobTryFailure(retObject, hpcServerJob, autoCleanup) : 
  #Error completing job on cluster:
#Error in try({ : 
```

Whereas this works:

```r
out <- RxXdfData("/user/sshuser/ftest", fileSystem=hd, createCompositeSet=TRUE)
rxFactors(mth, outFile=out, factorInfo="am")
```

**Comment by hongooi73** [comment]
This applies to output data sources.

**Comment by hongooi73** [comment]
TFS item 78046
