### ISSUE TITLE
Joining on factors failing on HDFS/Spark

### ISSUE THREAD

**Issue by hongooi73** [RevolutionAnalytics/dplyrXdf#56]
```
> z <- left_join(xdf1f, xdf2f)
Joining by: "a"
ERROR: org.apache.spark.SparkException: Job aborted due to stage failure: Task 0 in stage 1544.0 failed 4 times, most recent failure: Lost task 0.3 in stage 1544.0 (TID 43573, 10.0.0.7, executor 9): java.lang.Exception: Factor column a__new__ stored in XDFD footer is missing in XDFM 
at com.microsoft.scaler.spark.xdf.XCxdfDataFile$$anonfun$replaceGlobalLevelsMappingWithLocalIfAny$2.apply(XCxdfDataFile.scala:289) 
at com.microsoft.scaler.spark.xdf.XCxdfDataFile$$anonfun$replaceGlobalLevelsMappingWithLocalIfAny$2.apply(XCxdfDataFile.scala:287) 
at scala.collection.IndexedSeqOptimized$class.foreach(IndexedSeqOptimized.scala:33) 
at scala.collection.mutable.ArrayOps$ofRef.foreach(ArrayOps.scala:186) 
at com.microsoft.scaler.spark.xdf.XCxdfDataFile.replaceGlobalLevelsMappingWithLocalIfAny(XCxdfDataFile.scala:287) 
at com.microsoft.scaler.spark.xdf.XCxdfDataFile.readBody(XCxdfDataFile.scala:260) 
at com.microsoft.scaler.spark.xdf.XCxdfDataFile.readDF(XCxdfDataFile.scala:248) 
at com.microsoft.scaler.spark.task.ConvertCxdfToDfTask.com$microsoft$scaler$spark$task$ConvertCxdfToDfTask$$dataMapFunction(ConvertCxdfToDfTask.scala:69) 
at com.microsoft.scaler.spark.task.ConvertCxdfToDfTask$$anonfun$1.apply(ConvertCxdfToDfTask.scala:50) 
at com.microsoft.scaler.spark.task.ConvertCxdfToDfTask$$anonfun$1.apply(ConvertCxdfToDfTask.scala:50) 
at scala.collection.Iterator$$anon$12.nextCur(Iterator.scala:434) 
at scala.collection.Iterator$$anon$12.hasNext(Iterator.scala:440) 
at scala.collection.Iterator$$anon$11.hasNext(Iterator.scala:408) 
at scala.collection.Iterator$$anon$11.hasNext(Iterator.scala:408) 
at org.apache.spark.sql.catalyst.expressions.GeneratedClass$GeneratedIterator.processNext(Unknown Source) 
at org.apache.spark.sql.execution.BufferedRowIterator.hasNext(BufferedRowIterator.java:43) 
at org.apache.spark.sql.execution.WholeStageCodegenExec$$anonfun$8$$anon$1.hasNext(WholeStageCodegenExec.scala:377) 
at scala.collection.Iterator$$anon$11.hasNext(Iterator.scala:408) 
at org.apache.spark.shuffle.sort.BypassMergeSortShuffleWriter.write(BypassMergeSortShuffleWriter.java:126) 
at org.apache.spark.scheduler.ShuffleMapTask.runTask(ShuffleMapTask.scala:96) 
at org.apache.spark.scheduler.ShuffleMapTask.runTask(ShuffleMapTask.scala:53) 
at org.apache.spark.scheduler.Task.run(Task.scala:99) 
at org.apache.spark.executor.Executor$TaskRunner.run(Executor.scala:322) 
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) 
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) 
at java.lang.Thread.run(Thread.java:748) 
 
Driver stacktrace: 
Error in rxCompleteClusterJob(hpcServerJob, consoleOutput, autoCleanup) : 
  No results available - final job state: failed
```

**Comment by hongooi73** [comment]
Underlying cause is #57
